# Numpy
- based on https://github.com/mephistopheies/mlworkshop39_042017/blob/master/0_python_intro/%D0%A3%D0%BF%D1%80%D0%B0%D0%B6%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F.ipynb

<img src="trainings1.jpg" />

## Task 0
- import numpy

In [4]:
import numpy as np

## Task 1
- print version of numpy

In [2]:
np.__version__

'1.18.1'

## Task 2
- create 1d vector of zeros of size 10

In [7]:
v1=np.zeros((1,10))

In [8]:
v1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Task 3
- create 1d vector filled with ones of size 10

In [46]:
v2=np.ones((10,1))
v2

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

## Task 4
- create 1d vector filled with ones of size 10,

In [18]:
v3=np.ones((10,))
v3

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Task 5
- crete 1d vector filled with numbers from 10 to 49

In [23]:
v4=np.arange(10,50,1)
v4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## Task 6
- create any 1d vector, then reverce it, such that last element will be on the first position

In [48]:
#np.flip(v4)
v4[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Task 7
- create 2d 3x3 array / matrix, filled with numbers from 0 to 8

In [39]:
v5=np.arange(9).reshape(3,3)
v5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Task 8
- create 3x3 matrix filled with ones

In [41]:
v6=np.ones((3,3))
v6

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Task 9
- create 3x3 matrix filled with random numbers

In [60]:
v7=np.random.rand(3,3)
v7

array([[0.01122508, 0.52732741, 0.15476722],
       [0.90292571, 0.26606597, 0.73531678],
       [0.60259039, 0.47979998, 0.78440305]])

## Task 10
- create 3x3x3 array filled with random numbers

In [8]:
v8=np.random.randint(10,50,size=(3,3,3))
v8

array([[[32, 46, 47],
        [12, 27, 37],
        [47, 32, 27]],

       [[18, 43, 24],
        [21, 29, 42],
        [41, 36, 17]],

       [[12, 43, 45],
        [27, 27, 22],
        [32, 35, 39]]])

## Task 11
- create 10x10 matrix filled with random numbers and find minimal and maximal elements

In [14]:
v9=np.random.randint(1,1000,size=(10,10))
v9
v9.min(), v9.max()

(5, 985)

## Task 12
- create a random 1d vector of size 30 and find average of them

In [22]:
v10 = np.random.randint(50,100, size=(30,1))
v10
v10.mean()

73.3

## Task 13
- create 5x5 matrix, which has ones on a "frame" and zeros inside

In [43]:
v11=np.zeros(25).reshape(5,5)
v11[0,:]=1
v11[4,:]=1
v11[:,0]=1
v11[:,4]=1
v11

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Task 14
- create 8x8 matrix
- fill it with ones and zeros in a "chess" order
- **don't use** `tile` funtion

In [45]:
v12=np.zeros(64).reshape(8,8)
for row in range(8):
    for col in range(8):
        if(row+col) % 2 == 0:
            v12[row,col]=1
v12

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

## Task 15
- create 8x8 matrix
- fill it with ones and zeros in a "chess" order
- **use** `tile` funtion

In [127]:
a=np.zeros(25).reshape(5,5)
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [136]:
#a[0:2:1, 0:2:1]
a[::2, ::1] = 1
a
#b=np.zeros(64).reshape(8,8)
#b[::2,::2]=1
#b[1::2, 1::2]=1
#b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [123]:
a[0:4:1, 0:4:1]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

## Task 16
- create two random matrices 5x3 and 3x2
- multiply them

In [150]:
m1=np.random.randint(1,15, size=(5,3))
m2=np.random.randint(1,6, size=(3,2))
m1, m2
m1.dot(m2)

array([[ 62, 119],
       [ 47, 130],
       [ 21,  76],
       [ 37,  71],
       [ 47,  94]])

## Task 17
- create array of size 100 filled with random numbers from 0 to 10
- chenge sign of all numbers which are in a range between 3 and 8

In [169]:
a1=np.random.randint(1,10, size=(100,1))
a1[(a1<=8) & (a1>=3)]

array([4, 5, 7, 6, 8, 6, 8, 5, 8, 7, 7, 6, 7, 6, 7, 8, 3, 5, 8, 4, 8, 3,
       4, 7, 6, 5, 6, 6, 8, 6, 3, 7, 4, 5, 4, 6, 4, 5, 5, 8, 6, 3, 7, 5,
       4, 6, 6, 3, 8, 6, 4, 5, 3, 6, 8, 5, 3, 8, 8, 3, 5, 4, 5])

## Task 18
- create a matrix 5x5 such that each row would be a 1d array filled with numbers from 0 to 4

In [213]:
v=np.arange(0,5).reshape(1,5)
m18=np.repeat(v, repeats = 5, axis = 0)
m18

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

## Task 19
- create 1d vector of size 100 filled with random values from range 0-1, excluding boundary values (no exact 0/1)

In [220]:
v19=np.random.uniform(0,1,size=(100,1))
v19

array([[0.4378998 ],
       [0.8212857 ],
       [0.27038901],
       [0.73432201],
       [0.91955986],
       [0.58905894],
       [0.21634412],
       [0.29527126],
       [0.48230092],
       [0.74686595],
       [0.66919568],
       [0.38794325],
       [0.01485281],
       [0.64105301],
       [0.72665599],
       [0.51054366],
       [0.55590221],
       [0.57914137],
       [0.37878354],
       [0.14347928],
       [0.82380605],
       [0.3688431 ],
       [0.6008049 ],
       [0.15854564],
       [0.92881647],
       [0.93150804],
       [0.37036928],
       [0.15337397],
       [0.27176684],
       [0.12817278],
       [0.23965201],
       [0.82981889],
       [0.08387281],
       [0.9078899 ],
       [0.00503579],
       [0.07103207],
       [0.90640604],
       [0.2768613 ],
       [0.40780423],
       [0.15154948],
       [0.08543673],
       [0.32650657],
       [0.39104169],
       [0.46438115],
       [0.21006695],
       [0.14006963],
       [0.23232674],
       [0.400

## Task 20
- create a 10x2 random matrix filled with number from range 0-100
- consider it as points in Cartesian plain
- convert to polar system of coordinates

In [260]:
m20=np.random.randint(0,100,size=(10,2))
x,y=m20[:,0],m20[:,1]
r = np.sqrt(x**2 + y**2)
t =  np.degrees(np.arctan2(y,x))
print(m20)
print(r)
print(t)

[[ 5 79]
 [ 6 71]
 [80 70]
 [88 48]
 [12 28]
 [73 58]
 [82 60]
 [15 63]
 [43 29]
 [82 19]]
[ 79.15806971  71.25307011 106.30145813 100.23971269  30.46309242
  93.23625904 101.60708637  64.76109943  51.86520992  84.17244205]
[86.3785153  85.16958004 41.18592517 28.61045967 66.80140949 38.46786331
 36.19320731 76.60750225 33.99645915 13.04563706]


## Task 21
- create random 13x13 matrix, replace maximal element to zero

In [381]:
m21=np.random.randint(1,50, size=(13,13))
print(m21)
print('-'*50)
m_ind=np.where(m21 == np.amax(m21))
#print(m_ind)
r=m_ind[0]
c=m_ind[1]
for j in range(len(c)):
    m21[m_ind[0][j]][m_ind[1][j]]=0
print(m21)

[[20 22 47 40 47 18 10 26 18 35 38  1 34]
 [34 18  2 48 18 39 37 33 11 20 12 48 24]
 [10 49 37 14 37 17 42 16 45 31 33  3 22]
 [ 3 28 12 40 46 37 26 39 16 42 21  9 43]
 [13 29 23  6  3 45 23  8 24 47 49  2 23]
 [28 30 43 38 27  5  9 11 43 32 45 10 11]
 [ 7  4  1 21 48 39 15 10 30 21 47 11  7]
 [ 4  5 19  7  2 42 35 18 35 25 15 20 42]
 [29 12 12 45 28 22  2 38 38 21 38 26 39]
 [14 21 45 38 23  7 29 17 21 17 36 34  9]
 [15 44 10 32 10 11 46  6 47 34 13  2 32]
 [10 22  8 30 36 11 38 33 32 30 46 33 36]
 [49 30 10 41 48 24  2  3  9 46 21 49 10]]
--------------------------------------------------
[[20 22 47 40 47 18 10 26 18 35 38  1 34]
 [34 18  2 48 18 39 37 33 11 20 12 48 24]
 [10  0 37 14 37 17 42 16 45 31 33  3 22]
 [ 3 28 12 40 46 37 26 39 16 42 21  9 43]
 [13 29 23  6  3 45 23  8 24 47  0  2 23]
 [28 30 43 38 27  5  9 11 43 32 45 10 11]
 [ 7  4  1 21 48 39 15 10 30 21 47 11  7]
 [ 4  5 19  7  2 42 35 18 35 25 15 20 42]
 [29 12 12 45 28 22  2 38 38 21 38 26 39]
 [14 21 45 38 23  7 29 1

## Task 22
- create two 1d arrays with random values
- make a Cauchy matrix from them $C (C_{ij} = \frac{1}{x_i - y_j})$

In [404]:
x=np.array([1,2,3,4])
y=np.array([5,6,7])
print(x,y)
x=x.reshape((-1,1))
print(x,y)
diff=x-y
print(diff)
c_m = 1.0/diff
print(c_m)


[1 2 3 4] [5 6 7]
[[1]
 [2]
 [3]
 [4]] [5 6 7]
[[-4 -5 -6]
 [-3 -4 -5]
 [-2 -3 -4]
 [-1 -2 -3]]
[[-0.25       -0.2        -0.16666667]
 [-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


In [414]:
lenx=len(x)
leny=len(y)
xm=np.repeat(x,leny)
print(xm)
print(y)
ym=np.tile(y,lenx)
print(ym)
cm=(1.0/(xm-ym)).reshape([lenx,leny])
print(cm)

[1 1 1 2 2 2 3 3 3 4 4 4]
[5 6 7]
[5 6 7 5 6 7 5 6 7 5 6 7]
[[-0.25       -0.2        -0.16666667]
 [-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


## Task 23
- create an array of random `float` numbers and convert it to `int`

In [421]:
fl=np.random.uniform(low=1.0, high=5, size=10)
flToInt=fl.astype(int)
print(fl)
print(flToInt)

[4.51681953 3.81696722 4.35173765 1.35440413 1.31185367 1.15888055
 1.87465893 3.20703372 4.39133766 2.6818755 ]
[4 3 4 1 1 1 1 3 4 2]


## Task 24
- create 1d array of numbers from 0 to 15
- put each of them in random positions inside 4x4 matrix

In [440]:
a1=np.arange(0,16)
m24=np.array(np.random.choice(a1,15, replace=False))
print(a1)
print(m24)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[14  8  0 15  3 11  6  9  2 10 13  7  1  5  4]


## Task 25
- create random 100x50 matrix
- deduct avarage of each row from correspondatn rows

In [454]:
m25=np.random.randint(1,100,size=(100,50))
print(m25)
avg_r=np.mean(m25, axis=1)[:, np.newaxis]
m25_res = m25 - avg_r
print(m25_res)

[[28 95 62 ... 54  8 20]
 [48 50 32 ... 77 28 97]
 [66 76 56 ...  8 51  9]
 ...
 [44 17 71 ... 84 30 16]
 [59 88 32 ...  7 42 84]
 [82 81 39 ... 91 44 37]]
[[-24.42  42.58   9.58 ...   1.58 -44.42 -32.42]
 [ -3.6   -1.6  -19.6  ...  25.4  -23.6   45.4 ]
 [ 23.3   33.3   13.3  ... -34.7    8.3  -33.7 ]
 ...
 [ -1.02 -28.02  25.98 ...  38.98 -15.02 -29.02]
 [ 10.08  39.08 -16.92 ... -41.92  -6.92  35.08]
 [ 32.7   31.7  -10.3  ...  41.7   -5.3  -12.3 ]]


## Task 26 
- create random 10x10 matrix
- extract diagonal elements and put them into 1d array

In [458]:
m26=np.random.randint(100,size=(10,10))
m26_dg=np.diag(m26)
print(m26)
print(m26_dg)

[[41 83 14 76 52 45 36 96 51 41]
 [91 69 99 10 15 86 13 83  5 16]
 [20 28 65 59 88 48 41 84 19 53]
 [ 0 43 22 77 35  0 47 13 74 45]
 [88 93 99 44 86 67 78 15 94 80]
 [ 6 94 17 42 79 29 20 70 53  8]
 [63 72 18 24 31  1 47 24 63 24]
 [33 94  0 21 84 60 33 36 89 78]
 [94 73 51 30 70 17 20 20 41 75]
 [58  2 23 15 80 33 81 33 69 40]]
[41 69 65 77 86 29 47 36 41 40]


## Task 27
- given a vector `[1, 2, 3, 4, 5]`
- build a new vertor with three zeros between each element

In [531]:
v27=np.array([1,2,3,4,5])
z=np.array([0,0,0,0])
res=np.empty( (v27.size + z.size,), dtype=v27.dtype )
res[0::2]=v27
res[1::2]=z
res

array([1, 0, 2, 0, 3, 0, 4, 0, 5])